class StatusLog:
    WRONG_START_BYTE = False
    RIGHT_START_BYTE = True

    INVALID_CHECK_SUM = False
    VALID_CHECK_SUM   = True

class ByteDex:
    def getByteFromStr(byte):
        return int(byte, 16)
    
    HEADER_LENGTH            = 4 #bytes read from serial
    TYPE_BYTE_POSITION       = 2
    TIME_FIRST_BYTE_POSITION = 3
    TOTAL_TIME_BYTES         = 8
    SLOPE_BYTE_POSITION      = TIME_FIRST_BYTE_POSITION + TOTAL_TIME_BYTES

    YEAR    = TIME_FIRST_BYTE_POSITION + 0
    MONTH   = TIME_FIRST_BYTE_POSITION + 1
    DAY     = TIME_FIRST_BYTE_POSITION + 2
    HOUR    = TIME_FIRST_BYTE_POSITION + 3
    MINUTE  = TIME_FIRST_BYTE_POSITION + 4
    SECOND  = TIME_FIRST_BYTE_POSITION + 5
    MILS_FH = TIME_FIRST_BYTE_POSITION + 6 #FIRST  HALF OF THE NUMBER OF MILISECONDS
    MILS_SH = TIME_FIRST_BYTE_POSITION + 7 #SECOND HALF OF THE NUMBER OF MILISECONDS

    START_BYTE           = 0xAA
    TRIGGER_BYTE         = 0xAB
    BOOT_BYTE            = 0xAC
    ETHERNET_STATUS_BYTE = 0xAD

    RISING_SLOPE         = 0x01
    FALLING_SLOPE        = 0x10

    NOT_CONNECTED          = 0     
    CONNECTED              = 1
    IP_FIRST_BYTE_POSITION = 3
    TOTAL_IP_BYTES         = 4
    IP_FIRST_BYTE          = IP_FIRST_BYTE_POSITION + 0
    IP_SECOND_BYTE         = IP_FIRST_BYTE_POSITION + 1
    IP_THIRD_BYTE          = IP_FIRST_BYTE_POSITION + 2
    IP_FORTH_BYTE          = IP_FIRST_BYTE_POSITION + 3
    ETHERNET_STATUS_POS    = IP_FIRST_BYTE_POSITION + TOTAL_IP_BYTES 

class Format:
    TIME_DISPLAY_FORMAT = '0>2'
    TIME_MS_DISPLAY_FORMAT = '0>3'
    YEAR_OFFSET = 2000